language: c

script:
  - make test CONFIG=config/config-ci.mk
  - (cd test; ./test -v)

before_install:
  - pip install --user -q cpp-coveralls

after_success:
  - coveralls -b . -e test -e include --gcov-options '\-lp'

